INSERT INTO
    `activity` (`label`)
VALUES
    ('Agence ou société commerciale'),
    ('Agriculture'),
    ('Art et design'),
    ('Industrie automobile'),
    ('Construction'),
    ('Biens de consommation'),
    ('Éducation'),
    ('Ingénierie'),
    ('Divertissement'),
    ('Services financiers'),
    ('Activités de restauration'),
    ('Jeux'),
    ('Fonction publique'),
    ('Services de santé'),
    ("Décoration d'intérieur"),
    ('Interne'),
    ('Légal'),
    ('Industrie'),
    ('Commercialisation'),
    ('Exploitation minière et logistique'),
    ('Non lucratif'),
    ('Publication et médias Web'),
    ('Vente au détail (e-commerce et hors ligne)'),
    ('Immobilier'),
    ('Service'),
    ('Technologie'),
    ('Télécommunications'),
    ('Tourisme / hôtellerie'),
    ('Création de sites web'),
    ('Développement web'),
    ('Maroquinerie'),
    ('Pêche maritime');

INSERT INTO
    `country` (`id`, `name`)
VALUES
    (1, 'Afghanistan'),
    (2, 'Åland Islands'),
    (3, 'Albania'),
    (4, 'Algeria'),
    (5, 'American Samoa'),
    (6, 'Andorra'),
    (7, 'Angola'),
    (8, 'Anguilla'),
    (9, 'Antarctica'),
    (10, 'Antigua and Barbuda'),
    (11, 'Argentina'),
    (12, 'Armenia'),
    (13, 'Aruba'),
    (14, 'Australia'),
    (15, 'Austria'),
    (16, 'Azerbaijan'),
    (17, 'Bahamas'),
    (18, 'Bahrain'),
    (19, 'Bangladesh'),
    (20, 'Barbados'),
    (21, 'Belarus'),
    (22, 'Belgium'),
    (23, 'Belize'),
    (24, 'Benin'),
    (25, 'Bermuda'),
    (26, 'Bhutan'),
    (27, 'Bolivia'),
    (28, 'Bosnia and Herzegovina'),
    (29, 'Botswana'),
    (30, 'Bouvet Island'),
    (31, 'Brazil'),
    (32, 'British Indian Ocean Territory'),
    (33, 'Brunei Darussalam'),
    (34, 'Bulgaria'),
    (35, 'Burkina Faso'),
    (36, 'Burundi'),
    (37, 'Cambodia'),
    (38, 'Cameroon'),
    (39, 'Canada'),
    (40, 'Cape Verde'),
    (41, 'Cayman Islands'),
    (42, 'Central African Republic'),
    (43, 'Chad'),
    (44, 'Chile'),
    (45, 'China'),
    (46, 'Christmas Island'),
    (47, 'Cocos (Keeling) Islands'),
    (48, 'Colombia'),
    (49, 'Comoros'),
    (50, 'Congo'),
    (51, 'Congo, The Democratic Republic of The'),
    (52, 'Cook Islands'),
    (53, 'Costa Rica'),
    (54, "Cote D'ivoire"),
    (55, 'Croatia'),
    (56, 'Cuba'),
    (57, 'Cyprus'),
    (58, 'Czech Republic'),
    (59, 'Denmark'),
    (60, 'Djibouti'),
    (61, 'Dominica'),
    (62, 'Dominican Republic'),
    (63, 'Ecuador'),
    (64, 'Egypt'),
    (65, 'El Salvador'),
    (66, 'Equatorial Guinea'),
    (67, 'Eritrea'),
    (68, 'Estonia'),
    (69, 'Ethiopia'),
    (70, 'Falkland Islands (Malvinas)'),
    (71, 'Faroe Islands'),
    (72, 'Fiji'),
    (73, 'Finland'),
    (74, 'France'),
    (75, 'French Guiana'),
    (76, 'French Polynesia'),
    (77, 'French Southern Territories'),
    (78, 'Gabon'),
    (79, 'Gambia'),
    (80, 'Georgia'),
    (81, 'Germany'),
    (82, 'Ghana'),
    (83, 'Gibraltar'),
    (84, 'Greece'),
    (85, 'Greenland'),
    (86, 'Grenada'),
    (87, 'Guadeloupe'),
    (88, 'Guam'),
    (89, 'Guatemala'),
    (90, 'Guernsey'),
    (91, 'Guinea'),
    (92, 'Guinea-Bissau'),
    (93, 'Guyana'),
    (94, 'Haiti'),
    (95, 'Heard Island and Mcdonald Islands'),
    (96, 'Holy See (Vatican City State)'),
    (97, 'Honduras'),
    (98, 'Hong Kong'),
    (99, 'Hungary'),
    (100, 'Iceland'),
    (101, 'India'),
    (102, 'Indonesia'),
    (103, 'Iran, Islamic Republic of'),
    (104, 'Iraq'),
    (105, 'Ireland'),
    (106, 'Isle of Man'),
    (107, 'Israel'),
    (108, 'Italy'),
    (109, 'Jamaica'),
    (110, 'Japan'),
    (111, 'Jersey'),
    (112, 'Jordan'),
    (113, 'Kazakhstan'),
    (114, 'Kenya'),
    (115, 'Kiribati'),
    (116, "Korea, Democratic People's Republic of"),
    (117, 'Korea, Republic of'),
    (118, 'Kuwait'),
    (119, 'Kyrgyzstan'),
    (120, "Lao People's Democratic Republic"),
    (121, 'Latvia'),
    (122, 'Lebanon'),
    (123, 'Lesotho'),
    (124, 'Liberia'),
    (125, 'Libyan Arab Jamahiriya'),
    (126, 'Liechtenstein'),
    (127, 'Lithuania'),
    (128, 'Luxembourg'),
    (129, 'Macao'),
    (130, 'Macedonia, The Former Yugoslav Republic of'),
    (131, 'Madagascar'),
    (132, 'Malawi'),
    (133, 'Malaysia'),
    (134, 'Maldives'),
    (135, 'Mali'),
    (136, 'Malta'),
    (137, 'Marshall Islands'),
    (138, 'Martinique'),
    (139, 'Mauritania'),
    (140, 'Mauritius'),
    (141, 'Mayotte'),
    (142, 'Mexico'),
    (143, 'Micronesia, Federated States of'),
    (144, 'Moldova, Republic of'),
    (145, 'Monaco'),
    (146, 'Mongolia'),
    (147, 'Montenegro'),
    (148, 'Montserrat'),
    (149, 'Morocco'),
    (150, 'Mozambique'),
    (151, 'Myanmar'),
    (152, 'Namibia'),
    (153, 'Nauru'),
    (154, 'Nepal'),
    (155, 'Netherlands'),
    (156, 'Netherlands Antilles'),
    (157, 'New Caledonia'),
    (158, 'New Zealand'),
    (159, 'Nicaragua'),
    (160, 'Niger'),
    (161, 'Nigeria'),
    (162, 'Niue'),
    (163, 'Norfolk Island'),
    (164, 'Northern Mariana Islands'),
    (165, 'Norway'),
    (166, 'Oman'),
    (167, 'Pakistan'),
    (168, 'Palau'),
    (169, 'Palestinian Territory, Occupied'),
    (170, 'Panama'),
    (171, 'Papua New Guinea'),
    (172, 'Paraguay'),
    (173, 'Peru'),
    (174, 'Philippines'),
    (175, 'Pitcairn'),
    (176, 'Poland'),
    (177, 'Portugal'),
    (178, 'Puerto Rico'),
    (179, 'Qatar'),
    (180, 'Reunion'),
    (181, 'Romania'),
    (182, 'Russian Federation'),
    (183, 'Rwanda'),
    (184, 'Saint Helena'),
    (185, 'Saint Kitts and Nevis'),
    (186, 'Saint Lucia'),
    (187, 'Saint Pierre and Miquelon'),
    (188, 'Saint Vincent and The Grenadines'),
    (189, 'Samoa'),
    (190, 'San Marino'),
    (191, 'Sao Tome and Principe'),
    (192, 'Saudi Arabia'),
    (193, 'Senegal'),
    (194, 'Serbia'),
    (195, 'Seychelles'),
    (196, 'Sierra Leone'),
    (197, 'Singapore'),
    (198, 'Slovakia'),
    (199, 'Slovenia'),
    (200, 'Solomon Islands'),
    (201, 'Somalia'),
    (202, 'South Africa'),
    (
        203,
        'South Georgia and The South Sandwich Islands'
    ),
    (204, 'Spain'),
    (205, 'Sri Lanka'),
    (206, 'Sudan'),
    (207, 'Suriname'),
    (208, 'Svalbard and Jan Mayen'),
    (209, 'Swaziland'),
    (210, 'Sweden'),
    (211, 'Switzerland'),
    (212, 'Syrian Arab Republic'),
    (213, 'Taiwan, Province of China'),
    (214, 'Tajikistan'),
    (215, 'Tanzania, United Republic of'),
    (216, 'Thailand'),
    (217, 'Timor-leste'),
    (218, 'Togo'),
    (219, 'Tokelau'),
    (220, 'Tonga'),
    (221, 'Trinidad and Tobago'),
    (222, 'Tunisia'),
    (223, 'Turkey'),
    (224, 'Turkmenistan'),
    (225, 'Turks and Caicos Islands'),
    (226, 'Tuvalu'),
    (227, 'Uganda'),
    (228, 'Ukraine'),
    (229, 'United Arab Emirates'),
    (230, 'United Kingdom'),
    (231, 'United States'),
    (232, 'Uruguay'),
    (233, 'Uzbekistan'),
    (234, 'Vanuatu'),
    (235, 'Venezuela'),
    (236, 'Viet Nam'),
    (237, 'Western Sahara'),
    (238, 'Yemen'),
    (239, 'Zambia'),
    (240, 'Zimbabwe');

INSERT INTO
    `currency` (
        `id`,
        `code`,
        `label`,
        `symbol`,
        `digitAfterComma`
    )
VALUES
    (1, 'AFN', 'Afghan afghani', '؋', 2),
    (2, 'EUR', 'Euro', '€', 2),
    (3, 'ALL', 'Albanian lek', 'L', 2),
    (4, 'DZD', 'Algerian dinar', 'د.ج', 2),
    (5, 'USD', 'United States Dollar', '$', 2),
    (6, 'AOA', 'Angolan kwanza', 'Kz', 2),
    (7, 'XCD', 'East Caribbean dollar', '$', 2),
    (8, 'ARS', 'Argentine peso', '$', 2),
    (9, 'AMD', 'Armenian dram', '֏', 2),
    (10, 'AWG', 'Aruban florin', 'ƒ', 2),
    (11, 'AUD', 'Australian dollar', '$', 2),
    (12, 'AZN', 'Azerbaijani manat', '₼', 2),
    (13, 'BSD', 'Bahamian dollar', '$', 2),
    (14, 'BHD', 'Bahraini dinar', '.د.ب', 2),
    (15, 'BDT', 'Bangladeshi taka', '৳', 2),
    (16, 'BBD', 'Barbadian dollar', '$', 2),
    (17, 'BYN', 'New Belarusian ruble', 'Br', 2),
    (18, 'BZD', 'Belize dollar', '$', 2),
    (19, 'XOF', 'West African CFA franc', 'Fr', 2),
    (20, 'BMD', 'Bermudian dollar', '$', 2),
    (21, 'BTN', 'Bhutanese ngultrum', 'Nu.', 2),
    (22, 'BOB', 'Bolivian boliviano', 'Bs.', 2),
    (23, 'USD', 'United States dollar', '$', 2),
    (
        24,
        'BAM',
        'Bosnia and Herzegovina convertible mark',
        'KM',
        2
    ),
    (25, 'BWP', 'Botswana pula', 'P', 2),
    (26, 'NOK', 'Norwegian krone', 'kr', 2),
    (27, 'BRL', 'Brazilian real', 'R$', 2),
    (28, 'BND', 'Brunei dollar', '$', 2),
    (29, 'BGN', 'Bulgarian lev', 'лв', 2),
    (30, 'BIF', 'Burundian franc', 'Fr', 2),
    (31, 'CVE', 'Cape Verdean escudo', 'Esc', 2),
    (32, 'KHR', 'Cambodian riel', '៛', 2),
    (33, 'XAF', 'Central African CFA franc', 'Fr', 2),
    (34, 'CAD', 'Canadian dollar', '$', 2),
    (35, 'KYD', 'Cayman Islands dollar', '$', 2),
    (36, 'CLP', 'Chilean peso', '$', 2),
    (37, 'CNY', 'Chinese yuan', '¥', 2),
    (38, 'COP', 'Colombian peso', '$', 2),
    (39, 'KMF', 'Comorian franc', 'Fr', 2),
    (40, 'CDF', 'Congolese franc', 'Fr', 2),
    (41, 'NZD', 'New Zealand dollar', '$', 2),
    (42, 'CRC', 'Costa Rican colón', '₡', 2),
    (43, 'CUC', 'Cuban convertible peso', '$', 2),
    (
        44,
        'ANG',
        'Netherlands Antillean guilder',
        'ƒ',
        2
    ),
    (45, 'CZK', 'Czech koruna', 'Kč', 2),
    (46, 'DKK', 'Danish krone', 'kr', 2),
    (47, 'DJF', 'Djiboutian franc', 'Fr', 2),
    (48, 'DOP', 'Dominican peso', '$', 2),
    (49, 'EGP', 'Egyptian pound', '£', 2),
    (50, 'ERN', 'Eritrean nakfa', 'Nfk', 2),
    (51, 'SZL', 'Swazi lilangeni', 'L', 2),
    (52, 'ETB', 'Ethiopian birr', 'Br', 2),
    (53, 'FKP', 'Falkland Islands pound', '£', 2),
    (54, 'FJD', 'Fijian dollar', '$', 2),
    (55, 'XPF', 'CFP franc', 'Fr', 2),
    (56, 'GMD', 'Gambian dalasi', 'D', 2),
    (57, 'GEL', 'Georgian Lari', 'ლ', 2),
    (58, 'GHS', 'Ghanaian cedi', '₵', 2),
    (59, 'GIP', 'Gibraltar pound', '£', 2),
    (60, 'GTQ', 'Guatemalan quetzal', 'Q', 2),
    (61, 'GBP', 'British pound', '£', 2),
    (62, 'GNF', 'Guinean franc', 'Fr', 2),
    (63, 'GYD', 'Guyanese dollar', '$', 2),
    (64, 'HTG', 'Haitian gourde', 'G', 2),
    (65, 'HNL', 'Honduran lempira', 'L', 2),
    (66, 'HKD', 'Hong Kong dollar', '$', 2),
    (67, 'HUF', 'Hungarian forint', 'Ft', 2),
    (68, 'ISK', 'Icelandic króna', 'kr', 2),
    (69, 'INR', 'Indian rupee', '₹', 2),
    (70, 'IDR', 'Indonesian rupiah', 'Rp', 2),
    (71, 'IRR', 'Iranian rial', '﷼', 2),
    (72, 'IQD', 'Iraqi dinar', 'ع.د', 2),
    (73, 'ILS', 'Israeli new shekel', '₪', 2),
    (74, 'JMD', 'Jamaican dollar', '$', 2),
    (75, 'JPY', 'Japanese yen', '¥', 2),
    (76, 'JOD', 'Jordanian dinar', 'د.ا', 2),
    (77, 'KZT', 'Kazakhstani tenge', '₸', 2),
    (78, 'KES', 'Kenyan shilling', 'Sh', 2),
    (79, 'KPW', 'North Korean won', '₩', 2),
    (80, 'KRW', 'South Korean won', '₩', 2),
    (81, 'KWD', 'Kuwaiti dinar', 'د.ك', 2),
    (82, 'KGS', 'Kyrgyzstani som', 'с', 2),
    (83, 'LAK', 'Lao kip', '₭', 2),
    (84, 'LBP', 'Lebanese pound', 'ل.ل', 2),
    (85, 'LSL', 'Lesotho loti', 'L', 2),
    (86, 'LRD', 'Liberian dollar', '$', 2),
    (87, 'LYD', 'Libyan dinar', 'ل.د', 2),
    (88, 'CHF', 'Swiss franc', 'Fr', 2),
    (89, 'MOP', 'Macanese pataca', 'P', 2),
    (90, 'MGA', 'Malagasy ariary', 'Ar', 2),
    (91, 'MWK', 'Malawian kwacha', 'MK', 2),
    (92, 'MYR', 'Malaysian ringgit', 'RM', 2),
    (93, 'MVR', 'Maldivian rufiyaa', '.ރ', 2),
    (94, 'MRO', 'Mauritanian ouguiya', 'UM', 2),
    (95, 'MUR', 'Mauritian rupee', '₨', 2),
    (96, 'MXN', 'Mexican peso', '$', 2),
    (97, 'MDL', 'Moldovan leu', 'L', 2),
    (98, 'MNT', 'Mongolian tögrög', '₮', 2),
    (99, 'MAD', 'Moroccan dirham', 'د.م.', 2),
    (100, 'MZN', 'Mozambican metical', 'MT', 2),
    (101, 'MMK', 'Burmese kyat', 'Ks', 2),
    (102, 'NAD', 'Namibian dollar', '$', 2),
    (103, 'NPR', 'Nepalese rupee', '₨', 2),
    (104, 'NIO', 'Nicaraguan córdoba', 'C$', 2),
    (105, 'NGN', 'Nigerian naira', '₦', 2),
    (106, 'MKD', 'Macedonian denar', 'ден', 2),
    (107, 'OMR', 'Omani rial', 'ر.ع.', 2),
    (108, 'PKR', 'Pakistani rupee', '₨', 2),
    (109, 'PAB', 'Panamanian balboa', 'B/.', 2),
    (110, 'PGK', 'Papua New Guinean kina', 'K', 2),
    (111, 'PYG', 'Paraguayan guaraní', '₲', 2),
    (112, 'PEN', 'Peruvian sol', 'S/.', 2),
    (113, 'PHP', 'Philippine peso', '₱', 2),
    (114, 'PLN', 'Polish złoty', 'zł', 2),
    (115, 'QAR', 'Qatari riyal', 'ر.ق', 2),
    (116, 'RON', 'Romanian leu', 'lei', 2),
    (117, 'RUB', 'Russian ruble', '₽', 2),
    (118, 'RWF', 'Rwandan franc', 'Fr', 2),
    (119, 'SHP', 'Saint Helena pound', '£', 2),
    (120, 'WST', 'Samoan tālā', 'T', 2),
    (
        121,
        'STD',
        'São Tomé and Príncipe dobra',
        'Db',
        2
    ),
    (122, 'SAR', 'Saudi riyal', 'ر.س', 2),
    (123, 'RSD', 'Serbian dinar', 'дин.', 2),
    (124, 'SCR', 'Seychellois rupee', '₨', 2),
    (125, 'SLL', 'Sierra Leonean leone', 'Le', 2),
    (126, 'SGD', 'Singapore dollar', '$', 2),
    (127, 'SBD', 'Solomon Islands dollar', '$', 2),
    (128, 'SOS', 'Somali shilling', 'Sh', 2),
    (129, 'ZAR', 'South African rand', 'R', 2),
    (130, 'FKP', 'Falkland Islands Pound', '£', 2),
    (131, 'SSP', 'South Sudanese pound', '£', 2),
    (132, 'LKR', 'Sri Lankan rupee', 'Rs', 2),
    (133, 'SDG', 'Sudanese pound', 'ج.س.', 2),
    (134, 'SRD', 'Suri"label"se dollar', '$', 2),
    (135, 'SEK', 'Swedish krona', 'kr', 2),
    (136, 'SYP', 'Syrian pound', '£', 2),
    (137, 'TWD', 'New Taiwan dollar', '$', 2),
    (138, 'TJS', 'Tajikistani somoni', 'ЅМ', 2),
    (139, 'TZS', 'Tanzanian shilling', 'Sh', 2),
    (140, 'THB', 'Thai baht', '฿', 2),
    (141, 'TOP', 'Tongan paʻanga', 'T$', 2),
    (
        142,
        'TTD',
        'Trin"id"ad and Tobago dollar',
        '$',
        2
    ),
    (143, 'TND', 'Tunisian dinar', 'د.ت', 2),
    (144, 'TRY', 'Turkish lira', '₺', 2),
    (145, 'TMT', 'Turkmenistan manat', 'm', 2),
    (146, 'UGX', 'Ugandan shilling', 'Sh', 2),
    (147, 'UAH', 'Ukrainian hryvnia', '₴', 2),
    (
        148,
        'AED',
        'United Arab Emirates dirham',
        'د.إ',
        2
    ),
    (149, 'UYU', 'Uruguayan peso', '$', 2),
    (150, 'UZS', "Uzbekistani so'm", "so'm", 2),
    (151, 'VUV', 'Vanuatu vatu', 'Vt', 2),
    (152, 'VEF', 'Venezuelan bolívar', 'Bs S', 2),
    (153, 'VND', 'Viet"label"se đồng', '₫', 2),
    (154, 'YER', 'Yemeni rial', '﷼', 2),
    (155, 'ZMW', 'Zambian kwacha', 'ZK', 2);

INSERT INTO
    `payment_condition` (`label`, `description`)
VALUES
    ('Payable à réception', ''),
    ('Echéance à la fin du mois', ''),
    ('Echéance à la fin du mois prochain', ''),
    ('Personalisé', '');

INSERT INTO
    `app_config` (`key`, `value`)
VALUES
    (
        'quotation_sequence',
        '{"label": "quotation", "prefix": "QUO", "dynamicSequence": "yyyy-MM", "next": 1}'
    ),
    (
        'invoice_sequence',
        '{"label": "invoice", "prefix": "INV", "dynamicSequence": "yyyy-MM", "next": 1}'
    );

INSERT INTO
    `tax` (`label`, `rate`, `isSpecial`)
VALUES
    ('FODEC', 0.01, TRUE),
    ('TVA', 0.19, FALSE);

INSERT INTO
    `address` (
        `address`,
        `address2`,
        `region`,
        `zipcode`,
        `countryId`
    )
VALUES
    (
        '188 Avenue 14 Janvier',
        'Apt. 855',
        'Bizerte',
        '7000',
        222
    );

INSERT INTO
    `cabinet` (
        `enterpriseName`,
        `email`,
        `phone`,
        `taxIdNumber`,
        `activityId`,
        `currencyId`,
        `addressId`
    )
VALUES
    (
        'Zedney Creative EMEA',
        'contact@zedney.com',
        '+216 72 428 365',
        '1538414/L/A/M/0000',
        8,
        143,
        1
    );